[window]
opacity = 0.7
dynamic_title = true

[window.padding]
x = 10
y = 10

[font]
size = 14.0

[colors.primary]
background = "#000300"
foreground = "#efefef"

[colors.cursor]
cursor = "#e00304"

[colors.normal]
black = "#03070a"
red = "#e00304"
green = "#14ff9d"
yellow = "#e4f53f"
blue = "#1476ff"
magenta = "#ff14eb"
cyan = "#14ebff"
white = "#efefef"

[colors.bright]
black = "#010203"
red = "#ff2914"
green = "#00f56e"
yellow = "#ebff14"
blue = "#0099ff"
magenta = "#ee00d9"
cyan = "#00cff5"
white = "#fafafa"

[cursor.style]
shape = "Beam"
blinking = "On"

[scrolling]
history = 40000

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
args = [
    "--login",
]
